#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
sudo apt-get update
sudo apt-get -y install haproxy

#edit config file
server_config=\
"
frontend mysolomon.tech-frontend
	bind *:80
	mode http
	default_backend mysolomon.tech-backend
backend mysolomon.tech-backend
	balance roundrobin
	server 136272-web-01 18.234.80.126 check
	server 136272-web-02 52.201.211.91 check
"
echo "$server_config" | sudo tee -a /etc/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLE=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
